Dz13 + Timer
mrdemqn/KakhanouskiAndroidPvt pull request #13
Opened 2019-07-31 15:21 UTC by mrdemqn

2019-08-01 04:40 UTC, tim-teacher requested changes

2019-08-01 04:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz11/mvvm/ViewModel.kt
> +        disposable = carRepository
а где отписываетесь то? Необходимо в onCleared() это делать.

2019-08-01 04:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz11/mvvm/ViewModel.kt
> +            .subscribeOn(newThread())
лучше использовать Schedulers.IO()

2019-08-01 04:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz11/mvvm/timer/TimerActivity.kt
> +    private var disposableBag: CompositeDisposable? = null
что за Bag))), сompositeDisposable назовите и все, Bag другой программист точно не поймест, а вот сompositeDisposable - все сразу ясно.

2019-08-01 04:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz11/mvvm/timer/TimerActivity.kt
> +
две пустые строки, забыли про скрипт?)

2019-08-01 04:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz11/mvvm/timer/TimerActivity.kt
> +
этот метод можно удалить, достаточно только onNext() и onError() переопределить.

2019-08-01 04:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz11/mvvm/timer/TimerActivity.kt
> +
пустая строка перед закрываюзей ковычкой скрипт тоже не пропускает, ну вообщем пройдитесь kotlin lint по коду.

2019-08-01 04:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz11/mvvm/timer/TimerActivity.kt
> +        return Observable.create { subscriber ->
нее, у Rx куча готовых методов которые можно юзать, посмотрите interval например.

2019-08-01 04:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz9/Api.kt
> +    ): Call<CarResponse>
Зачем дублировать часть функционала? Если на Rx поменяли, то и используйте Rx.

2019-08-01 04:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz9/CarRepository.kt
> +    fun getCarByCoordinate(params: CoordinateParams, listener: CarRepositoryResult)
ну и тут тоже самое, этот метод можно удалить.

2019-08-02 11:15 UTC, tim-teacher approved these changes

2019-08-02 12:59 UTC, dgmedvedev approved these changes

2019-08-07 06:29 UTC, merged