Dz1
mrdemqn/KakhanouskiAndroidPvt pull request #2
Opened 2019-06-15 14:47 UTC by mrdemqn

2019-06-16 08:33 UTC, tim-teacher requested changes
Нужно поправить

2019-06-16 08:33 UTC, jushlwest commented on app/src/main/AndroidManifest.xml
> +        </activity>
можно закрыть тег стару />
<activity android:name=".pvt.dz0.dz0.Dz0MainActivity"/>

2019-06-16 08:33 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz0/dz0/Dz0MainActivity.kt
> +
2 пустых сроки

2019-06-16 08:33 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz0/dz0/Dz0MainActivity.kt
> +    fun inversion() {
добавить private

2019-06-16 08:33 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz0/dz1/Dz1FlagsActivity.kt
> +
2 пустые строки

2019-06-16 08:33 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz0/dz1/Dz1MenuActivity.kt
> +
очень много пустых и не нужных строк :)

2019-06-16 08:33 UTC, jushlwest commented on app/src/main/res/layout/activity_dz1_flags.xml
> +<RelativeLayout
а где ScrollView? Явно же что все флаги могут не поместиться на экране

2019-06-16 08:33 UTC, jushlwest commented on app/src/main/res/layout/activity_dz1_flags.xml
> +    <TextView
Зачем TextView если вы не используете его возможности, можно использовать View

2019-06-16 08:33 UTC, jushlwest commented on app/src/main/res/layout/activity_dz1_menu.xml
> +
максимум одна пустая строка должна быть

2019-06-16 13:52 UTC, tim-teacher requested changes
Так а TextView чего не заменили?

2019-06-16 14:50 UTC, mrdemqn commented
Я поменял, но всё перестало работать.

2019-06-16 14:51 UTC, mrdemqn commented on app/src/main/res/layout/activity_dz1_flags.xml
> +    <TextView
Я поменял, но всё перестало работать

2019-06-18 10:52 UTC, eugenia-shumeika approved these changes

2019-06-18 11:48 UTC, tim-teacher approved these changes

2019-06-18 14:10 UTC, merged